version: '3'

services:
  e28-web:
    container_name: 'e28_apache_2'
    build: ./builds/web
    ports:
      - "8080:80"
    volumes:
      - ./volumes/html:/var/www/html
    links:
      - e28-db

  e28-db:
    container_name: 'e28_mysql'
    image: mysql:8.0.14
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
    working_dir: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=e28
